# This file is a template, and might need editing before it works on your project.
# Official language image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/ruby/tags/
image: "crystallang/crystal:latest" # latest can be replaced with any version, i.e. 0.19.3

# Pick zero or more services to be used on all builds.
# Only needed when using a docker container to run your tests in.
# Check out: http://docs.gitlab.com/ce/ci/docker/using_docker_images.html#what-is-service
# services:
#   - mysql:latest
#   - redis:latest
#   - postgres:latest

# variables:
#   POSTGRES_DB: database_name

# Cache shards in between builds
cache:
  paths:
    - libs

# This is a basic example for a shard or script which doesn't use
# services such as redis or postgres
before_script:
  - apt-get update -qq && apt-get install -y -qq libxml2-dev
  - crystal -v # Print out Crystal version for debugging
  - shards

# If you are using built-in Crystal Spec.
spec:
  script:
  - crystal spec

# If you are using minitest.cr
minitest:
  script:
  - crystal test/spec_test.cr # change to the file(s) you execute for tests
